import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                window: true,
                document: true,
                location: true,
                setTimeout: true,
                clearTimeout: true,
                setInterval: true,
                clearInterval: true,
                console: true,
                alert: true,
                Node: true,
                Element: true,
                HTMLMediaElement: true,
                MutationObserver: true,
                NodeList: true,
                NodeFilter: true,
                ResizeObserver: true,
                AbortController: true,
                IDBKeyRange: true,
                indexedDB: true,
                history: true,
                URL: true,
                // Node.js全局变量
                module: true,
                require: true,
                __dirname: true,
                import: true,
                process: true,
                // 浏览器全局变量
                localStorage: true,
                sessionStorage: true,
                fetch: true,
                navigator: true,
                performance: true,
                requestAnimationFrame: true,
                cancelAnimationFrame: true,
                requestIdleCallback: true,
                cancelIdleCallback: true,
                getComputedStyle: true,
                CustomEvent: true,
                DOMException: true,
                Document: true,
                DocumentFragment: true,
                HTMLInputElement: true,
                Event: true,
                KeyboardEvent: true,
                MouseEvent: true,
                IntersectionObserver: true,
                WebSocket: true,
                Blob: true,
                FileReader: true,
                FormData: true,
                Headers: true,
                Response: true,
                Request: true,
                btoa: true,
                atob: true,
                crypto: true,
                JSON: true,
                Math: true,
                Date: true,
                RegExp: true,
                Map: true,
                Set: true,
                WeakMap: true,
                WeakSet: true,
                Promise: true,
                Symbol: true,
                Array: true,
                Object: true,
                String: true,
                Number: true,
                Boolean: true,
                parseInt: true,
                parseFloat: true,
                isNaN: true,
                isFinite: true,
                encodeURIComponent: true,
                decodeURIComponent: true,
                encodeURI: true,
                decodeURI: true,
                escape: true,
                unescape: true,
                Infinity: true,
                NaN: true,
                undefined: true,
                // Greasemonkey/Tampermonkey 用户脚本全局变量
                GM: true,
                GM_info: true,
                GM_getValue: true,
                GM_setValue: true,
                GM_deleteValue: true,
                GM_listValues: true,
                GM_xmlhttpRequest: true,
                GM_download: true,
                GM_openInTab: true,
                GM_notification: true,
                GM_setClipboard: true,
                GM_registerMenuCommand: true,
                GM_unregisterMenuCommand: true,
                unsafeWindow: true
            }
        },
        plugins: {
            '@stylistic': stylistic
        },
        rules: {
            // 代码风格规则
            '@stylistic/semi': ['error', 'never'],
            '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
            '@stylistic/indent': ['error', 4, { SwitchCase: 1, MemberExpression: 1, FunctionDeclaration: { parameters: 'first' }, ArrayExpression: 'first', ObjectExpression: 'first' }],
            '@stylistic/comma-dangle': ['error', 'never'],
            '@stylistic/object-curly-spacing': ['error', 'always', { 'arraysInObjects': false, 'objectsInObjects': false }],
            '@stylistic/no-trailing-spaces': 'error',
            '@stylistic/eol-last': ['error', 'always'],
            '@stylistic/array-element-newline': ['error', 'consistent'],
            '@stylistic/array-bracket-newline': ['error', 'consistent'],
            '@stylistic/array-bracket-spacing': ['error', 'never'],
            '@stylistic/array-callback-return': 'off',
            '@stylistic/space-before-function-paren': [
                'error',
                {
                    anonymous: 'always',
                    named: 'always',
                    asyncArrow: 'always'
                }
            ],
            '@stylistic/keyword-spacing': [
                'error',
                {
                    after: true,
                    before: true
                }
            ],
            '@stylistic/function-paren-newline': ['error', 'consistent'],
            '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
            '@stylistic/space-infix-ops': 'error',
            '@stylistic/comma-spacing': ['error', { before: false, after: true }],
            '@stylistic/key-spacing': ['error', { 'afterColon': true }],
            '@stylistic/no-multiple-empty-lines': ['error', { max: 0, maxEOF: 0, maxBOF: 0 }],
            '@stylistic/padded-blocks': ['error', 'never'],
            '@stylistic/lines-between-class-members': ['error', 'never'],
            '@stylistic/arrow-spacing': ['error', { 'before': true, 'after': true }],
            '@stylistic/arrow-parens': ['error', 'as-needed'],
            '@stylistic/no-multi-spaces': ['error'],
            'arrow-body-style': ['error', 'as-needed'],
            'no-unused-vars': 'warn',
            'no-var': 'error',
            'prefer-const': 'error',
            'eqeqeq': ['error', 'always'],
            'curly': ['error', 'multi-line'],
            'dot-notation': 'error',
            // 错误预防
            'no-debugger': 'error',
            'no-dupe-keys': 'error',
            'no-undef': 'error'
        }
    },
    {
        ignores: [
            '.history/',
            'node_modules/',
            'dist/',
            'webpack.config.js',
            'babel.config.js',
            'build/*.js',
            'src/assets',
            'public',
            '*.user.js',
            '*.meta.js',
            'everythingIsBasedOnThisFile.js'
        ]
    }
]
